### PR TITLE
Update INPUT command to use embedded Reader

### PR DESCRIPTION
**Pull request by andydotxyz**
Complete the move to embedded Reader/Writer
Remove the test.v requirement to run the INPUT test

### CODE REVIEW

**Comment by andydotxyz** [comment]
Sorry I didn't notice that this was mostly addressed by you already oops!
Maybe you can see if there is anything here you want and pull it out, otherwise just close it :)

**Comment by andydotxyz** [comment]
It looks like the main difference is that you still use fmt.Printf in the INPUT prompt

**Comment by skx** [comment]
> It looks like the main difference is that you still use fmt.Printf in the INPUT prompt

That's a good observation. if you submitted a PR just for that I'd accept it.  Otherwise I'll deal with it in the morning.

**Comment by andydotxyz** [comment]
Quite right - I will try and rebase my work so you don't have to unpick this all

**Comment by andydotxyz** [comment]
Replaced with #100

**Pull request closed without merging**
